# Generated by Django 4.0 on 2024-03-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='serviceArea',
            field=models.ManyToManyField(related_name='couriers', to='MyApp.ServiceArea'),
        ),
        migrations.DeleteModel(
            name='EnquiryForm',
        ),
    ]
