# Generated by Django 4.0 on 2024-03-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_courier_servicearea_delete_enquiryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courierWght', models.CharField(default=0, max_length=100)),
                ('TravelBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.travelby')),
                ('courierService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.courier')),
                ('destination_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_destination', to='MyApp.servicearea')),
                ('serviceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.servicetype')),
                ('source_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_source', to='MyApp.servicearea')),
            ],
        ),
    ]
