# Generated by Django 4.0 on 2024-03-31 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_courier_servicearea_courier_servicearea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costtable',
            old_name='from_wait_per_gram',
            new_name='from_weight_per_gram',
        ),
        migrations.RenameField(
            model_name='costtable',
            old_name='to_wait_per_gram',
            new_name='to_weight_per_gram',
        ),
    ]
