# Generated by Django 4.0 on 2024-03-31 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_rename_from_wait_per_gram_costtable_from_weight_per_gram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryform',
            name='shipmentType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.shipmenttype'),
            preserve_default=False,
        ),
    ]
